version: '3.8'
services:
  database:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: databse
    ports:
      - "5432:5432"
    volumes:
      - .postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      SERVICES: "dynamodb,lambda,s3,ses,sns,sqs,ssm,sts"
      EDGE_PORT: 4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - ./.localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data: