
name: Tests CI

on:
  push:
    branches:
      - feat/tests-ci

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
            
        steps:
            - uses: actions/checkout@v3
            
            - name: Cache Node.js modules
              uses: actions/cache@v3
              with:
                    path: ~/.npm
                    key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                      ${{ runner.os }}-node-${{ matrix.node-version }}-
            
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            
            - name: step
              run: pwd

            - name: Install dependencies
              run: cd /home/runner/work/video-processing-challenge/video-processing-challenge/src/lambda-create-signed-upload-url && npm ci

            #- name: Increase Node.js memory limit
            #  run: export NODE_OPTIONS="--max-old-space-size=4096"

            - name: Unit tests
              run: npm run test:ci
