name: Tests CI

on:
  push:
    branches:
      - feat/tests-ci

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
            
        steps:
            - uses: actions/checkout@v3
            
            - name: Cache Node.js modules
              uses: actions/cache@v3
              with:
                    path: ~/.npm
                    key: ${{ runner.os }}-node-22.x-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                      ${{ runner.os }}-node-22.x-
            
            - name: Use Node.js 22.x
              uses: actions/setup-node@v3
              with:
                  node-version: 22.x

            - name: Install dependencies
              working-directory: ./src/lambda-create-signed-upload-url
              run: npm ci

            - name: Unit tests
              working-directory: ./src/lambda-create-signed-upload-url
              run: npm run test:ci

            - name: Check test coverage
              working-directory: ./src/lambda-create-signed-upload-url
              run: |
                COVERAGE=$(npm run coverage --silent)
                if [ "$COVERAGE" -lt 80 ]; then
                  echo "Test coverage is below 80%"
                  exit 1
                fi
